package-lock.json, package.json, packages/tests/package.json, packages/ui/Accordion/Accordion.js, packages/ui/Accordion/AccordionItem.js, packages/ui/Modal.js, packages/ui/Tabs.js, packages/ui/package.json
- Migrate usage of the `get:refs` event (b4809ea)
- Configure components' emitted events (946e7aa)
- Update NPM dependencies (38427ae)
=> [Hotfix] 0.1.1

composer.json, composer.lock, packages/docs/.symfony/composer.json, packages/docs/.symfony/composer.lock, packages/docs/.vitepress/config.ts, packages/docs/.vitepress/theme/custom.scss, packages/docs/components/atoms/Button/app.twig, packages/docs/components/atoms/Button/index.md, packages/docs/components/atoms/Cursor/index.md, packages/docs/components/atoms/Figure/index.md, packages/docs/components/molecules/Accordion/index.md, packages/docs/components/molecules/Modal/app.twig, packages/docs/components/molecules/Modal/index.md, packages/docs/components/molecules/Sticky/index.md, packages/ui/atoms/Button/Button.twig, packages/ui/atoms/Button/StyledButton.twig, packages/ui/atoms/Button/package.json, packages/ui/atoms/Cursor/Cursor.twig, packages/ui/atoms/Cursor/package.json, packages/ui/atoms/Figure/Figure.twig, packages/ui/atoms/Figure/package.json, packages/ui/molecules/Accordion/Accordion.twig, packages/ui/molecules/Accordion/package.json, packages/ui/molecules/Modal/Modal.twig, packages/ui/molecules/Modal/package.json, packages/ui/molecules/Sticky/Sticky.twig, packages/ui/molecules/Sticky/package.json
This PR adds standardization to the Twig templates and improve their documentation.
- Update `studiometa/twig-toolkit` extension to v1.2.0
- Standardize the Button Twig API (c7455e3)
- Standardize the Cursor Twig API (ab87a43)
- Standardize the Figure Twig API (6410c78)
- Standardize the Accordion Twig API (b56070d)
- Standardize the Modal Twig API (7e5bb51)
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/17"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Feature] Twig API standardization

composer.json, package-lock.json, package.json, packages/docs/guide/installation/index.md, packages/docs/guide/usage/index.md, packages/docs/package.json, packages/tests/package.json, packages/twig-extension/Extension.php, packages/ui/atoms/Figure/Figure.twig, packages/ui/package.json
- Fix default `fit` value for the Figure Twig template (dbcc06a, #18)
- Fix infinite loop when overriding package Twig templates (624e1b1, #18)
- Add support for custom attributes for the Figure Twig template (b3d0302, #18)
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/19"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Hotfix] 0.2.1

.github/workflows/tests.yml, package-lock.json, packages/docs/components/atoms/ScrollAnimation/ScrollAnimationParent.js, packages/docs/components/atoms/ScrollAnimation/app-parent.js, packages/docs/components/atoms/ScrollAnimation/app-parent.twig, packages/docs/components/atoms/ScrollAnimation/app.js, packages/docs/components/atoms/ScrollAnimation/app.twig, packages/docs/components/atoms/ScrollAnimation/index.md, packages/docs/components/atoms/ScrollAnimation/story-parent.md, packages/docs/components/atoms/ScrollAnimation/story.md, packages/docs/package.json, packages/tests/__snapshots__/index.spec.js.snap, packages/ui/atoms/ScrollAnimation/AbstractScrollAnimation.js, packages/ui/atoms/ScrollAnimation/ScrollAnimation.js, packages/ui/atoms/ScrollAnimation/ScrollAnimationChild.js, packages/ui/atoms/ScrollAnimation/ScrollAnimationChildWithEase.js, packages/ui/atoms/ScrollAnimation/ScrollAnimationParent.js, packages/ui/atoms/ScrollAnimation/ScrollAnimationWithEase.js, packages/ui/atoms/ScrollAnimation/animationScrollWithEase.js, packages/ui/atoms/ScrollAnimation/index.js, packages/ui/atoms/ScrollAnimation/package.json, packages/ui/atoms/index.js, packages/ui/package.json
Closes #30.
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/31"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Feature] Scroll animation

package-lock.json, packages/docs/components/molecules/Menu/index.md, packages/docs/components/molecules/Menu/mega-menu-responsive/Menu.js, packages/docs/components/molecules/Menu/mega-menu-responsive/app.js, packages/docs/components/molecules/Menu/mega-menu-responsive/app.twig, packages/docs/components/molecules/Menu/mega-menu-responsive/index.js, packages/docs/components/molecules/Menu/mega-menu-responsive/story.md, packages/docs/package.json, packages/docs/tailwind.config.cjs, packages/ui/atoms/LargeText/LargeText.js, packages/ui/atoms/LargeText/LargeText.twig, packages/ui/molecules/Menu/Menu.js, packages/ui/molecules/Menu/MenuBtn.js, packages/ui/molecules/Menu/MenuList.js, packages/ui/organisms/Frame/Frame.js, packages/ui/organisms/Frame/FrameAnchor.js, packages/ui/organisms/Frame/FrameForm.js, packages/ui/package.json
This PR updates the [@studiometa/js-toolkit](https://github.com/studiometa/js-toolkit) package to its latest version and updates components following the latest features.
- **Menu:** Add support for multiple `MenuBtn` when in clickable mode (10d0de1)
- Update `@studiometa/js-toolkit` package (#50)
- **LargeText:** Improve scroll performance (dc6ce0e)
- **Menu:** Fix a bug where submenus could not be opened in clickable mode (#50) 
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/50"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Feature] Update @studiometa/js-toolkit

packages/ui/molecules/Slider/Slider.js
This PR fixes a bug where the slider is glitching when navigating via drag. 
Fixes #65.
- **Slider:**
- Fix a glitch when navigating with drag (fix #65, #67, 7032615)
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/67"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Bugfix] Fix a glitch when navigating with drag on the Slider

packages/docs/components/molecules/Slider/stories/app.twig, packages/ui/molecules/Slider/Slider.js
- Fix a bug where sliders would jump on touch devices (#73, 840623b)
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/73"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Bugfix] Slider glitching on touch devices

composer.json, package-lock.json, package.json, packages/docs/package.json, packages/tests/package.json, packages/ui/molecules/Menu/MenuList.js, packages/ui/package.json
- Fix a bug where sliders would jump on touch devices (#73, 840623b)
=> [Release] 0.2.13

.github/workflows/tests.yml, package-lock.json, packages/docs/package.json, packages/ui/decorators/withTransition.ts, packages/ui/molecules/Modal/Modal.ts, packages/ui/molecules/Slider/SliderDrag.ts, packages/ui/organisms/Frame/FrameTarget.ts, packages/ui/package.json, scripts/shared.mjs
- Update [@studiometa/js-toolkit](https://github.com/studiometa/js-toolkit) from `2.5.0` to `2.6.0`
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/77"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Feature] JS Toolkit update

Dockerfile
- Add a Dockerfile to deploy the doc on release
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/84"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Feature] Deploy on release

CHANGELOG.md, composer.json, composer.lock, package-lock.json, package.json, packages/docs/.symfony/composer.lock, packages/docs/package.json, packages/tests/package.json, packages/ui/atoms/Figure/FigureTwicpics.twig, packages/ui/package.json
Please refer to [CHANGELOG.md](https://github.com/studiometa/ui/blob/hotfix/0.2.22/CHANGELOG.md) for details.
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/95"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Hotfix] 0.2.22

CHANGELOG.md, composer.json, package-lock.json, package.json, packages/docs/components/atoms/FigureTwicpics/js-api.md, packages/docs/components/atoms/FigureTwicpics/stories/twicpics/app.twig, packages/docs/components/atoms/FigureTwicpics/twig-api.md, packages/docs/package.json, packages/tests/package.json, packages/ui/atoms/Figure/Figure.ts, packages/ui/atoms/Figure/FigureTwicpics.ts, packages/ui/atoms/Figure/FigureTwicpics.twig, packages/ui/package.json
Please refer to [CHANGELOG.md](https://github.com/studiometa/ui/blob/hotfix/0.2.23/CHANGELOG.md) for details.
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/96"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Hotfix] 0.2.23

CHANGELOG.md, Dockerfile, composer.json, package-lock.json, package.json, packages/docs/package.json, packages/tests/package.json, packages/ui/package.json
See [CHANGELOG.md](https://github.com/studiometa/ui/blob/hotfix/0.2.26/CHANGELOG.md) for details.
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/111"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Hotfix] 0.2.26

.github/workflows/tests.yml, CHANGELOG.md, composer.json, package-lock.json, package.json, packages/docs/components/atoms/Button/twig-api.md, packages/docs/components/atoms/IconInline/examples.md, packages/docs/components/atoms/IconInlineImg/examples.md, packages/docs/package.json, packages/playground/package.json, packages/tests/package.json, packages/ui/package.json
- Fix docs build (1caef03)
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/122"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Hotfix] 0.2.30

CHANGELOG.md, composer.json, package-lock.json, package.json, packages/docs/package.json, packages/playground/package.json, packages/tests/package.json, packages/ui/molecules/Slider/Slider.ts, packages/ui/package.json
- **Slider:** fix buttons ([1460eb2](https://github.com/studiometa/ui/commit/1460eb2))
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/124"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Hotfix] 0.2.31

.github/workflows/release.yml, CHANGELOG.md, composer.json, package-lock.json, package.json, packages/docs/package.json, packages/playground/package.json, packages/tests/package.json, packages/ui/package.json
- Fix a package-lock conflict blocking GitHub Actions ([4a25aff](https://github.com/studiometa/ui/commit/4a25aff))
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/145"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Release] 0.2.37

.github/workflows/tests.yml, CHANGELOG.md, Dockerfile, package-lock.json, packages/docs/.vitepress/config.ts, packages/docs/guide/contributing/index.md, packages/docs/package.json, packages/docs/vite.config.js, packages/playground/lib/twig-loader.js, packages/playground/meta.config.js, packages/playground/package.json, packages/playground/static/deepmerge.js, packages/playground/static/js-toolkit-utils.js, packages/playground/static/js-toolkit.js, packages/playground/static/ui.js
Before this PR, we used an importmap in the playground to resolve the `@studiometa/*` packages with cdn.skypack.dev. 
This was not ideal for local development, as we could not test our new features or fixes in the playground. 
This PR solves this problem by changing the importmap to resolve the needed packages (`@studiometa/ui`, `@studiometa/js-toolkit` and `deepmerge`) with local files. These files are generated when building the playground (which is done automatically before building the docs) and are also rebuild on changes when in dev mode for the documentation with the `npm run docs:dev` command.
=> [Feature] Use the local files for the package in the playground 

CHANGELOG.md, packages/docs/components/atoms/Action/examples.md, packages/docs/components/atoms/Action/index.md, packages/docs/components/atoms/Action/js-api.md, packages/docs/components/atoms/Action/stories/close-modal-and-panel/app.js, packages/docs/components/atoms/Action/stories/close-modal-and-panel/app.twig, packages/tests/__snapshots__/index.spec.js.snap, packages/tests/atoms/Action.spec.js, packages/ui/atoms/Action/Action.ts, packages/ui/atoms/Action/index.ts, packages/ui/atoms/Action/package.json, packages/ui/atoms/index.ts
#161 
Add a JS component with no twig template to trigger action on other components.
Resolves #161
```html
<button
type="button"
data-component="Action"
data-option-on="click"
data-option-target="Panel Modal"
data-option-selector="[data-can-be-closed]"
data-option-method="close">
Close Panel & Modal with [data-can-be-closed]
</button>
```
[→ Show on the playground](https://ui.studiometa.dev/play/?html=eNqlVcluE0EQvfsrSkHgS8YOUrhEScR6A4GEOEWRVe4u20V6Sy9ZiPLvVE97HCcyCoI59VLLq1eveu5eAjtliiYYvy08xextmr4vOXs3%2FZ5vDem2meRrXo7hmvMK7kYABudkjmD8wfhE8A0dGXgFX7xG04zONGbsFLpuTp2qVvp8vC%2BemHM86mMAKIMpSZRIBjNfEfzq3hz0VgDVf6a8Dd6Ry2L0TmX2bvvWh3oy805ulWF1seMyY1xSdW%2FYeqQ7zCzlldd9HIG6wyCRIZW9QB%2F%2FsbT70T28vB%2BNjjVftdpO9q67RTEGVl1SkcjBwtANcCabOiV1UYSfJWVe3A7b0L0%2B2DuVaNIbsnPSrTPWS%2F5iKE37QtbN6ddPe% …
=> feat: Add the Action Atom

.ddev/config.yaml, CHANGELOG.md
Avoid this kind of error:
Added the latest LTS Node.js version to the ddev config, which respects the package.json requirements as well.
=> Add Node.js version to ddev config

CHANGELOG.md, packages/docs/demos/SectionSticky3dCards/index.md, packages/docs/demos/SectionSticky3dCards/stories/app.js, packages/docs/demos/SectionSticky3dCards/stories/app.twig
Add a demo for a section with sticky cards and a 3D effect while scrolling
=> [Feature] Demo: 3D sticky cards section

packages/docs/demos/FlyingCards/index.md, packages/docs/demos/FlyingCards/stories/app.js, packages/docs/demos/FlyingCards/stories/app.twig, packages/docs/demos/JukeboxCarousel/index.md, packages/docs/demos/JukeboxCarousel/stories/app.js, packages/docs/demos/JukeboxCarousel/stories/app.twig
=> Démo de cards volantes

CHANGELOG.md, composer.json, package-lock.json, package.json, packages/docs/package.json, packages/playground/package.json, packages/tests/package.json, packages/ui/package.json
- Add a `ui.ease` Twig global object to the Twig extension ([#195](https://github.com/studiometa/ui/pull/195))
- Add `AnchorNav`, `AnchorNavLink` and `AnchorNavTarget` JavaScript components ([#185](https://github.com/studiometa/ui/pull/185))
- Add JS and Twig `FigureVideo` and `FigureVideoTwicpics` components ([#193](https://github.com/studiometa/ui/pull/193))
- Add handling of POST requests for the `Frame` component ([#194](https://github.com/studiometa/ui/pull/194))
- Add documentaion for the `Frame` component ([#194](https://github.com/studiometa/ui/pull/194))
=> [Release] 0.2.48

CHANGELOG.md, packages/docs/demos/Navbar/index.md, packages/docs/demos/Navbar/stories/app.css, packages/docs/demos/Navbar/stories/app.js, packages/docs/demos/Navbar/stories/app.twig
Add a Navbar component demo.
Hide/show on scroll.
Example : [View on playground](https://ui.studiometa.dev/-/play/#html=eNpdU8uO2zAMvPcrCBfb0yp2Hi2ChZMeiuZU9AeCHGSZjtno4ZXkxIui%2F17KjtNFoQtFisOZoV0aSXb%2FAaBsUdboOQKoZZRCOdM5izbusp%2FyWkmfjTWlZQi7rKEBa4iuEwWQDRjFwFGjcQCKaIJQ3IkeWrHaQDeILVRncWu5xuj%2B8sK348fl93ROqeQ6qSi%2BiW3xqL9LVc4zN%2B44bPh8Pt3fzNn1YX3YcPaeqMQKKqkutWd6le69CCZLGpPK5awg4sCkNTTORhHQUOV0ne1L5WrcT4rLfLzAw4oyb5ejWfnk1hgHVJHcaCLfyJwheLXL2hi7lzzvbeh4YLugmC9X2yLfFsVXL23tzKezl1dWuJu8ykBqNjubCVbaqQvcRNNrzT4et0W4tidw1S8eyOu5ppZ8ovOOw8xnhhnN797EcgVGDuImjl82Hs0JzCBkH93sTPdY7WSIpwZGj%2FQZNKslexbauYD3BoDfT2ye5%2FXXaesWisVivYKnP%2FcywA%2FHg4C60Buonea3gSJIg%2FGZPeWvRkWMvQcG7yiQ4hGAmuICvqXqay%2FHauB%2BtLV8Bo%2Bdx5ZjZsdAFVh5R0bz2uMzhN5GQAnGaQyRZICWVNJNBsHV3ITUhzTkzCg09TI71zQ8XiaujJhY1sT9NjnJ …
=> [Feature] Demo: Navbar component

CHANGELOG.md, composer.json, package-lock.json, package.json, packages/docs/package.json, packages/playground/package.json, packages/tests/package.json, packages/ui/molecules/Reinsurance/Reinsurance.twig, packages/ui/package.json
Fix the condition for displaying the Reinsurance molecule icon.
=> [Hotfix] 0.2.51

CHANGELOG.md, package-lock.json, packages/docs/package.json, packages/tests/__utils__/mockIntersectionObserver.ts, packages/tests/atoms/Action.spec.ts, packages/tests/atoms/Cursor.spec.ts, packages/tests/atoms/DataBind.spec.ts, packages/tests/atoms/DataModel.spec.ts, packages/tests/molecules/Accordion/AccordionItem.spec.ts, packages/tests/molecules/Accordion/index.spec.ts, packages/tests/molecules/AnchorNav.spec.ts, packages/tests/molecules/Modal.spec.ts, packages/tests/molecules/Tabs.spec.ts, packages/tests/package.json, packages/tests/primitives/Draggable.spec.ts, packages/ui/molecules/Modal/Modal.ts, packages/ui/package.json
No issue.
This PR updates [@studiometa/js-toolkit](https://github.com/studiometa/js-toolkit) to its latest alpha version.
=> [Feature] Update @studiometa/js-toolkit to v3 

CHANGELOG.md, package-lock.json, packages/docs/migration-guides/0.2-1.0/index.md, packages/docs/package.json, packages/tests/__utils__/h.ts, packages/tests/__utils__/lifecycle.ts, packages/tests/molecules/Menu.spec.ts, packages/tests/molecules/Tabs.spec.ts, packages/ui/atoms/AnchorScrollTo/AnchorScrollTo.ts, packages/ui/atoms/LazyInclude/LazyInclude.ts, packages/ui/molecules/Accordion/AccordionCore.ts, packages/ui/molecules/AnchorNav/AnchorNav.ts, packages/ui/molecules/Menu/Menu.ts, packages/ui/molecules/Menu/MenuBtn.ts, packages/ui/molecules/Slider/Slider.ts, packages/ui/molecules/Slider/SliderDots.ts, packages/ui/molecules/Slider/SliderDrag.ts, packages/ui/molecules/Sticky/Sticky.ts, packages/ui/molecules/Tabs/Tabs.ts, packages/ui/organisms/Frame/Frame.ts, packages/ui/package.json
No issue.
This PR updates the dependency to the latest alpha version of [@studiometa/js-toolkit](https://github.com/studiometa/js-toolkit). It introduces some breaking changes regarding the arguments of the `on...` methods, see the migration guide for more details. 
- https://js-toolkit.studiometa.dev/guide/migration/v2-to-v3.html#the-on-method-arguments-have-been-refactored
- https://js-toolkit.studiometa.dev/guide/migration/v2-to-v3.html#lifecycle-methods-are-now-async
=> [Feature] Update @studiometa/js-toolkit 3.0.0-alpha.5 → 3.0.0-alpha.6

.github/workflows/publish.yml, CHANGELOG.md, composer.json, package-lock.json, package.json, packages/docs/package.json, packages/playground/package.json, packages/tests/package.json, packages/ui/package.json
- Fix publication with GitHub actions ([cb6381f](https://github.com/studiometa/ui/commit/cb6381f))
=> [Release] 1.0.0 alpha.5

.github/workflows/code-quality.yml, .github/workflows/tests.yml, .gitignore, CHANGELOG.md, composer.json, composer.lock, packages/twig-extension/Extension.php, phpunit.xml, tests/__snapshots__/AccordionTest__it_renders_an_Accordion__default_is__open_option_is_set_to_true__the_first_item_overrides_the_config_to_false__1.txt
No issue.
This PR upgrades the studiometa/twig-toolkit package to ^2.0 and sets the minimum twig/twig version to ^3.0.
See https://github.com/studiometa/twig-toolkit/pull/32 for more details.
=> [Feature] Upgrade dependencies 

CHANGELOG.md, package-lock.json, package.json, packages/docs/migration-guides/0.2-1.0/index.md, packages/docs/package.json, packages/tests/package.json, packages/ui/package.json
No issue.
Upgrade NPM dependencies and update migration guide.
=> [Feature] Upgrade NPM dependencies

CHANGELOG.md, package-lock.json, packages/docs/migration-guides/0.2-1.0/index.md, packages/docs/package.json, packages/ui/CircularMarquee/CircularMarquee.twig, packages/ui/Reinsurance/Reinsurance.twig, packages/ui/Tabs/Tabs.twig, prettier.config.js
#70
This PR implements the `attr` parameter for all remaining Twig templates not implementing it. Some variables have been renamed.
=> [Feature] Improve Twig components extensibility

CHANGELOG.md, packages/docs/components/Slider/index.md, packages/docs/components/Slider/js-api.md, packages/docs/components/Slider/js-api/index.md, packages/docs/components/Slider/js-api/slider-btn.md, packages/docs/components/Slider/js-api/slider-count.md, packages/docs/components/Slider/js-api/slider-dots.md, packages/docs/components/Slider/js-api/slider-drag.md, packages/docs/components/Slider/js-api/slider-item.md, packages/docs/components/Slider/js-api/slider-progress.md, packages/docs/components/Slider/js-api/slider.md, packages/ui/Slider/AbstractSliderChild.ts, packages/ui/Slider/Slider.ts, packages/ui/Slider/SliderBtn.ts, packages/ui/Slider/SliderCount.ts, packages/ui/Slider/SliderDots.ts, packages/ui/Slider/SliderDrag.ts, packages/ui/Slider/SliderItem.ts
No issue.
This PR removes some complex calculations made by the Slider component to treat visible items differently than the invisible ones.
=> [Feature] Simplify the Slider component

packages/docs/components/Draggable/examples.md, packages/docs/components/Draggable/stories/bounds/app.js, packages/docs/components/Draggable/stories/bounds/app.twig, packages/docs/components/Draggable/stories/dynamic-parent/app.js, packages/docs/components/Draggable/stories/dynamic-parent/app.twig, packages/ui/Draggable/Draggable.ts
No issue.
Improve Draggable bounds calculations.
=> [Feature] Improve Draggable bounds calculation

CHANGELOG.md, packages/docs/components/Hoverable/examples.md, packages/docs/components/Hoverable/index.md, packages/docs/components/Hoverable/js-api.md, packages/docs/components/Hoverable/stories/app.js, packages/docs/components/Hoverable/stories/app.twig, packages/tests/Hoverable/Hoverable.spec.ts, packages/tests/index.spec.ts, packages/ui/Hoverable/Hoverable.ts, packages/ui/Hoverable/index.ts, packages/ui/index.ts
No issue.
This PR adds a `Hoverable` component to easily move a target in its parent bounds.
See [this playground](https://ui.studiometa.dev/-/play/#html=eNrtWd1u0zAYvd9TfIoYAQm3WWFcVFsFAiEuuILLaZrcxEmMHDvyT0uZJnHF%2FcQD8G48AY%2BAkzpp2q1bO1Z%2BJN8ktmsff%2FZ3zkmcHiV0AjHDSh0HKSOfgGpSKBQTromEj0Zpms6a6hSlhjHI0clhNMlPg9GPr9%2FgQyyFbUzElB%2F1Ldpob68GTbDGKBZFKbgdfRy8FRMi8ZiRoJlPEoY1nZAFroolIRyqnikTU5TTJLH1cYYyiWfoaRQFoz2ABb4k6XGgscyIbmHxWAlmdAV7chAd7p9WAc8LirB0dW2dthoc4HwfKI%2BZSQiELwztv6GZkcTdenpKsxCmVOdwXncHUDIeQphrXaphv1%2FSWJmiV%2BZCC9U%2FGERRfQmfuN5Tmuh8CFVb05QTmuV6uS2ltiGMq71ohzZLG4KWhrStWsthGwzUO3MmSk0FP6vXdZZKUVgwUeKY6hlaxHLRFCjntp9Dmu%2BkHWA3flKisV3vomORXenW4tqwMFepkIUdUQ%2B4AMHZDParmqPHEkt2Qj0HmkmaQIZLdNChzZYTdoYvA7TgA%2FcjwGuSYsO0q90sAngZV%2FkJYClraJ41JPiwFLSKo1pbw%2FDeA8J69fTvqNI9SQqL …
=> [Feature] Add a `Hoverable` JS component

CHANGELOG.md, packages/docs/components/ImageGrid/examples.md, packages/docs/components/ImageGrid/index.md, packages/docs/components/ImageGrid/stories/block-image/app.js, packages/docs/components/ImageGrid/stories/block-image/app.twig, packages/docs/components/ImageGrid/twig-api.md, packages/ui/ImageGrid/ImageGrid.twig
No issue.
This PR fixes the responsive of the `ImageGrid` component and adds a new `image` block, allowing to customize the image output.
=> [Feature] ImageGrid

CHANGELOG.md, packages/ui/Icon/Icon.twig, packages/ui/LargeText/LargeText.twig
No issue.
Some Twig templates were using features which were not working with [Twig JS](https://github.com/twigjs/twig.js).
=> [Bugfix] Fix some Twig JS incompatibilities

CHANGELOG.md, packages/docs/components/Draggable/examples.md, packages/docs/components/Draggable/js-api.md, packages/docs/components/Draggable/stories/margin/app.css, packages/docs/components/Draggable/stories/margin/app.js, packages/docs/components/Draggable/stories/margin/app.twig, packages/docs/components/Draggable/stories/strict-bounds/app.css, packages/docs/components/Draggable/stories/strict-bounds/app.js, packages/docs/components/Draggable/stories/strict-bounds/app.twig, packages/tests/Draggable/Draggable.spec.ts, packages/ui/Draggable/Draggable.ts
No issue.
This PR contains multiple improvements and fixes for the [Draggable](https://ui.studiometa.dev/-/components/Draggable/) component.
- Add a `data-option-strict-fit-bounds` option to force the target to always stay in its parent bounds
- Add a new `drag-render` event, which is emitted after each render of the DOM
- Add progress information to the `props` property: `progressX` and `progressY` 
- Add a new `margin` option to configure inner or outer margins for the bounds
- Fix the name of the component, which made it unusable with the `Action` component
- Improve performance of bounds calculation (only when needed)
=> [Feature] Draggable improvements and fixes

CHANGELOG.md, CLAUDE.md, packages/docs/components/ScrollAnimation/examples.md, packages/docs/components/ScrollAnimation/js-api.md, packages/docs/components/ScrollAnimation/stories/sequence/app.js, packages/docs/components/ScrollAnimation/stories/sequence/app.twig, packages/docs/components/ScrollAnimation/stories/staggered/app.js, packages/docs/components/ScrollAnimation/stories/staggered/app.twig, packages/tests/ScrollAnimation/AbstractScrollAnimation.spec.ts, packages/tests/ScrollAnimation/ScrollAnimation.spec.ts, packages/tests/ScrollAnimation/ScrollAnimationChild.spec.ts, packages/tests/ScrollAnimation/ScrollAnimationParent.spec.ts, packages/tests/ScrollAnimation/index.spec.ts, packages/tests/__utils__/mockIntersectionObserver.ts, packages/ui/ScrollAnimation/AbstractScrollAnimation.ts, packages/ui/ScrollAnimation/ScrollAnimationChild.ts, packages/ui/ScrollAnimation/ScrollAnimationParent.ts
=> [Feature] Play range helpers
