- packages/ui/atoms/Button/Button.twig
- tests/__snapshots__/ButtonTest__it_renders_a_button__1.txt
- tests/__snapshots__/ButtonTest__it_renders_a_button_with_classes__1.txt
- tests/__snapshots__/ButtonTest__it_renders_a_button_with_type_submit__1.txt
- tests/__snapshots__/ButtonTest__it_renders_a_link__1.txt
- tests/atoms/Button/ButtonTest.php
Using `merge_html_attributes()` on `attr` and later on `attr.class` result in twice the class names when using `attr.class` to customise the button classes.
Exemple :
```
{% set attr = {
class: ['py-4']
} %}
{% extends '@ui-pkg/atoms/Button/Button.twig' %}
```
will output the following classes : `py-4 btn py-4`. 
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/22"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix Button class attribute merging twice

- packages/docs/components/atoms/LargeText/app.js
- packages/docs/components/atoms/LargeText/app.twig
- packages/docs/components/atoms/LargeText/index.md
- packages/docs/components/atoms/LargeText/story.md
- packages/ui/atoms/LargeText/LargeText.js
- packages/ui/atoms/LargeText/LargeText.twig
- packages/ui/atoms/LargeText/package.json
- **JS:** Add options to the `LargeText` component (#27)
- **Twig:** Add a Twig template for the `LargeText` component (#27)
- **Doc:** Add a demo for the `LargeText` component (#27)
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/27"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Feature] Add options to the `LargeText` component 

- packages/ui/atoms/Figure/Figure.js
As this component uses the `withMountWhenInView` decorator, the `src` attribute is set everytime the component re-enter the view which triggers a new network request for the image.
This behavior is especially visible when using a service like https://picsum.photos/ which serves a random image for each request.
This PR fixes it by checking if the `src` and `data-src` attributes already match before setting them.
> [Feature] Prevent unnecessary image requests

- packages/ui/primitives/Transition/Transition.js
The enter transition and the leave transition were not removing the previous classes when the `enterKeep` and `leaveKeep` options were enabled. This Pr fixes that by always removing the `enterTo` and `leaveTo` classes when adding the `leaveFrom` and `enterFrom` classes.
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/34"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Bugfix] Fix leave and enter transition for the `Transition` primitive

- packages/ui/molecules/Slider/Slider.js
- packages/ui/molecules/Slider/SliderItem.js
This PR improves extension of the Slider components.
- Expose the origins of the `Slider` component (c1a4316)
- Refactor the `SliderItem` style update in one `render` method (7252839)
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/41"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Bugfix] Slider expose origin

- packages/docs/.vitepress/config.ts
Update the docsDir entry with the new path for the docs. This fixes the `Edit this page on GitHub` link at the bottom of the pages.
> Update docs dir packages/vitepress > packages/docs

- packages/docs/components/molecules/Modal/app.twig
- packages/docs/components/molecules/Panel/app-bottom.twig
- packages/docs/components/molecules/Panel/app-left.twig
- packages/docs/components/molecules/Panel/app-right.twig
- packages/docs/components/molecules/Panel/app-top.twig
- packages/tests/molecules/Modal.spec.js
- packages/tests/molecules/Modal.template.html
- packages/ui/molecules/Modal/Modal.js
- packages/ui/molecules/Modal/Modal.twig
- packages/ui/molecules/Modal/StyledModal.twig
- packages/ui/molecules/Panel/StyledPanel.twig
- Update `open` an `close` refs on Modal & Panel components to be `open[]` and `close[]`
see #45 
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/49"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update open and close refs

- packages/ui/molecules/Modal/Modal.js
- Add `scrollLock`option to Modal to control the scroll status on documentElement (enable/disable)
Making a custom component based on `Modal` which does not need to lock the scroll on `documentElement`
- Where shall I add this inside the documentation ? Mostly the `*.twig` files parameters are documented, not the `*.js` component options. Any recommandations ?
- Not sure if it is possible to add a test for this with jest ?
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/43"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add scrollLock option to Modal

- packages/ui/atoms/Cursor/Cursor.js
- Add a scale option to Cursor component. Allow the customisation of the default scale for the component. For exemple to have a Cursor with a scale 0 as default.
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/48"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add a scale option to Cursor component

- packages/docs/components/atoms/Figure/index.md
- packages/docs/components/atoms/Figure/js-api.md
- packages/docs/components/atoms/Figure/stories/lazyload/app.twig
- packages/docs/components/atoms/Figure/stories/twicpics/app.twig
- packages/docs/components/atoms/Figure/twicpics-js-api.md
- packages/docs/components/atoms/Figure/twig-api.md
- packages/ui/atoms/Figure/Figure.js
- packages/ui/atoms/Figure/FigureTwicPics.js
- **Figure:** Add support for transition when using Figure with lazyload (#55)
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/55"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Feature] Add support for transition when using Figure with lazyload 

- composer.json
- package-lock.json
- package.json
- packages/docs/package.json
- packages/tests/package.json
- packages/ui/atoms/ScrollAnimation/AbstractScrollAnimation.ts
- packages/ui/package.json
- Fix a bug where ticked hook return function was not executed (#87, 8ed6e9d)
- Fix types (#87, a1152ae)
- Update @studiometa/js-toolkit 2.6.1 → 2.6.3 (#87, 8ed6e9d)
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/87"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Hotfix] 0.2.17

- packages/ui/atoms/Figure/Figure.ts
Terminate the `Figure` component to avoid weird behaviors when scrolling up and down when the image has already been loaded.
Closes #64.
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/89"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
- **Figure:** terminate component once the image is loaded (fix #64, #89)
> Terminate Figure component on image load

- composer.json
- package-lock.json
- package.json
- packages/docs/package.json
- packages/tests/package.json
- packages/ui/atoms/ScrollAnimation/AbstractScrollAnimation.ts
- packages/ui/package.json
- Fix `AbstractScrollAnimation` by removing `playRange` assignement
Component was throwing an error cause it has FreezedOptions: `Uncaught (in promise) TypeError: Cannot assign to read only property 'playRange' of object '#<Object>'` 
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/92"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Hotfix] 0.2.19

- CHANGELOG.md
- packages/ui/molecules/Slider/Slider.ts
- packages/ui/molecules/Slider/SliderBtn.ts
- Add the `contain` option to SliderBtn ([8407de8](https://github.com/studiometa/ui/commit/8407de8), [#101](https://github.com/studiometa/ui/issues/101))
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/105"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Feature] SliderBtn `contain` option

- CHANGELOG.md
- packages/docs/components/atoms/Figure/twig-api.md
- packages/ui/atoms/Figure/Figure.twig
- **Figure**
- Add the `placeholder_color` param to Figure ([51f625d](https://github.com/studiometa/ui/commit/51f625d), [#100](https://github.com/studiometa/ui/issues/100))
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/104"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Feature] Add a `placeholder_color` param to `Figure`

- CHANGELOG.md
- package-lock.json
- packages/playground/package.json
- packages/playground/src/js/components/Editor.ts
- packages/playground/src/js/components/Iframe.ts
- packages/playground/src/js/store/content.ts
- packages/playground/src/js/utils/js/index.ts
- packages/playground/src/js/utils/js/snippets.json
- packages/playground/src/js/utils/twig/index.ts
- packages/playground/src/js/utils/twig/snippets.json
- packages/playground/src/js/utils/twigRender.ts
- packages/playground/src/templates/pages/index.ts
- packages/playground/src/templates/pages/index.twig
- packages/playground/tailwind.config.cjs
- packages/playground/tsconfig.json
- patches/monaco-editor+0.34.1.patch
- **Playground:**
- add support for Twig and JS snippets autocompletion ([#114](https://github.com/studiometa/ui/pull/114), [54322cb](https://github.com/studiometa/ui/commit/54322cb))
- add support for Emmet in the HTML editor ([#114](https://github.com/studiometa/ui/pull/114), [883e039](https://github.com/studiometa/ui/commit/883e039))
- add support for import maps for the `@studiometa/` namespace ([#114](https://github.com/studiometa/ui/pull/114), [25052fd](https://github.com/studiometa/ui/commit/25052fd))
- **Playground:**
- fix Twig auto-indent not working for HTML elements ([#114](https://github.com/studiometa/ui/pull/114), [de6e560](https://github.com/studiometa/ui/commit/de6e560))
- fix a bug where HTML content was sometimes `undefined` …
> [Feature] Add Emmet and autocompletion snippets to the playground

- CHANGELOG.md
- packages/ui/atoms/Figure/FigureTwicpics.ts
- Fix the adding of the path in FigureTwicpics
<a href="https://gitpod.io/#https://github.com/studiometa/ui/pull/120"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix the adding of the path in FigureTwicpics

- CHANGELOG.md
- packages/docs/components/atoms/CircularMarquee/examples.md
- packages/docs/components/atoms/CircularMarquee/index.md
- packages/docs/components/atoms/CircularMarquee/stories/app-2.twig
- packages/docs/components/atoms/CircularMarquee/stories/app-3.twig
- packages/docs/components/atoms/CircularMarquee/stories/app-4.twig
- packages/docs/components/atoms/CircularMarquee/stories/app.js
- packages/docs/components/atoms/CircularMarquee/stories/app.twig
- packages/docs/components/atoms/CircularMarquee/twig-api.md
- packages/tests/__snapshots__/index.spec.js.snap
- packages/ui/atoms/CircularMarquee/CircularMarquee.ts
- packages/ui/atoms/CircularMarquee/CircularMarquee.twig
- packages/ui/atoms/CircularMarquee/index.ts
- packages/ui/atoms/index.ts
#66 
- Add a CircularMarquee Component, a spinning on scroll circular text. This is made using <svg> text capabilities.
- Resolves #66
> Feat: Add CircularMarquee atom component

- CHANGELOG.md
- packages/docs/components/atoms/FigureTwicpics/js-api.md
- packages/ui/atoms/Figure/FigureTwicpics.ts
This PR adds the support of the device pixel ratio, it will ensure TwicPics is returning a better image resolution for this device thus improving overall user experience.
The device pixel ratio isn't applied if the user agent is considered a bot/crawler to save bandwidth and resources.
> [Feature] Device Pixel Ratio support for `FigureTwicpics` component

- CHANGELOG.md
- packages/docs/components/atoms/FigureTwicpics/js-api.md
- packages/ui/atoms/Figure/FigureTwicpics.ts
Closes #125 
Add `disable` option that returns the original src instead of TwicPics's
> Add disable option for FigureTwicPics

- CHANGELOG.md
- packages/docs/components/organisms/Frame/index.md
- packages/docs/components/organisms/Frame/js-api.md
- packages/ui/organisms/Frame/Frame.ts
Add support for POST request for the Frame component. 
Based on current implementation on a project.
Not really convinced this is the my robust way of doing it. i'm also wondering if this is going to work onWindowPopstate.
**Requesting review to have feedback before processing to documentation, tests, etc**
> [Feature] Add support for post request in Frame component

- CHANGELOG.md
- packages/docs/components/atoms/DataBind/data-bind-js-api.md
- packages/tests/atoms/DataBind.spec.ts
- packages/ui/atoms/Data/DataBind.ts
No issue.
This PR adds a `value` property on the `DataBind` component. This property is a getter and setter which are aliases for the existing `get()` and `set(value)` methods.
> [Feature] Add a `value` property to the DataBind component

- CHANGELOG.md
- packages/docs/components/atoms/Action/examples.md
- packages/docs/components/atoms/Action/index.md
- packages/docs/components/atoms/Action/js-api.md
- packages/docs/components/atoms/Action/stories/basic/app-multiple.twig
- packages/docs/components/atoms/Action/stories/basic/app-selector.twig
- packages/docs/components/atoms/Action/stories/basic/app.js
- packages/docs/components/atoms/Action/stories/basic/app.twig
- packages/docs/components/atoms/Action/stories/close-modal-and-panel/app.twig
- packages/docs/components/atoms/Action/stories/counter/app.js
- packages/docs/components/atoms/Action/stories/counter/app.twig
- packages/docs/components/atoms/Action/stories/prevent-default/app.js
- packages/docs/components/atoms/Action/stories/prevent-default/app.twig
- packages/docs/components/atoms/Action/stories/target/app.js
- packages/docs/components/atoms/Action/stories/target/app.twig
- packages/playground/meta.config.js
- packages/tests/__snapshots__/index.spec.ts.snap
- packages/tests/__utils__/index.ts
- packages/tests/__utils__/lifecycle.ts
- packages/tests/atoms/Action.spec.ts
- packages/ui/atoms/Action/Action.ts
- packages/ui/atoms/Action/Target.ts
- packages/ui/atoms/Action/index.ts
- packages/ui/atoms/Button/Button.twig
- packages/ui/atoms/Icon/IconInline.twig
#258 
This PR implements the suggestion from #258.
See the [docs preview](https://261-develop-ui.ikko.studio/-/components/atoms/Action/) for usage and examples.
> [Feature] Improve the Action component

- CHANGELOG.md
- packages/tests/atoms/DataModel.spec.ts
- packages/ui/atoms/Data/DataBind.ts
- packages/ui/atoms/Data/DataModel.ts
#275
This PR fixes a bug where values for multiple checkboxes (name finishing by `[]`) were not tracked correctly and checkboxes could not be unchecked.
See #275 for a playground link.
> [Bugfix] Fix tracking values for multiple checkboxes

- CHANGELOG.md
- packages/docs/components/atoms/Action/stories/counter/app.js
- packages/docs/components/atoms/Action/stories/counter/app.twig
- packages/docs/components/atoms/DataBind/data-bind-js-api.md
- packages/docs/components/atoms/DataBind/data-computed-js-api.md
- packages/docs/components/atoms/DataBind/data-model-js-api.md
- packages/docs/components/atoms/DataBind/examples.md
- packages/docs/components/atoms/DataBind/stories/checkboxes.twig
- packages/tests/atoms/DataBind.spec.ts
- packages/tests/atoms/DataModel.spec.ts
- packages/ui/atoms/Data/DataBind.ts
- packages/ui/atoms/Data/DataComputed.ts
- packages/ui/atoms/Data/DataModel.ts
#279 
Before this PR, setting the value of a `DataBind` instance in JavaScript with `instance.value = newValue` did not update all other instances. The dispatch of a new value to all related instances was only happening when an `input` event was triggered on a `DataModel` component. 
This PR adds automatic dispatch of a new value set on a `DataBind` component.
> [Feature] Add support for automatic update of all Data... component on change

- CHANGELOG.md
- packages/docs/.vitepress/config.ts
- packages/docs/components/atoms/Action/index.md
- packages/docs/components/atoms/Action/js-api.md
- packages/docs/tailwind.config.cjs
- packages/tests/atoms/Action.spec.ts
- packages/ui/atoms/Action/Action.ts
#290 
This PR adds support for self reference in the effect of the `Action` component by:
- adding an extra `action` parameter that can be used in the `effect` callback
- defaulting to the current `Action` as target if the `target` option is not defined
> [Feature] Add support for `Action` self reference

- CHANGELOG.md
- packages/tests/__utils__/h.ts
- packages/tests/atoms/DataBind.spec.ts
- packages/tests/atoms/DataComputed.spec.ts
- packages/tests/atoms/DataEffect.spec.ts
- packages/tests/atoms/DataModel.spec.ts
- packages/ui/atoms/Data/DataBind.ts
#293
This PR fixes a bug where elements removed from the DOM were still included when computing the value of a multiple `DataBind` group. 
[Playground](https://294-develop-ui.ikko.studio/-/play/#html=eNrlkk1OwzAQhfc9xcgSBCRMqsKOJBKUFRIgwbLqwnGcYuHaVuxUaUvvjn%2BSUkEFB2AT25k3M9%2FzeHsChllYEdEyAznMklqp5AKSkjRx2SRzONmNRlnFV0AFMSZHtWAd%2BA%2BmSsCCaDxBxQjAa%2FzqdmVrrZJQEUucaKmVZNLm6JZaruQL04JQNlXSur8oZMBQXK%2FxBHSHr6Fc4NJx4avxGBrVyopVqOhzgcbkLI2dQvs09Hc7Z6tWTbQFXA7%2BnI8AJ0jJRAR1Jy51a8GuNcsRfWP0vVTdwAQ%2FHNy786OqmPgmUdo7w5IsD8rM5l%2BqwJCj7bbH2u0QpHsIo4kshtgHJZpbIvjGy7I0BCN6umd3HpmsvE0%2FHhfSRahylPiOywr9Dlr0fU5lafRNlupwpbphRwtO3bG1biAB6%2B8bOFT4Ui43Rw%2Bvz0%2BXxjZcLni9Pgvez6O%2BfwyWdRabJSpmc0fUsP853f5hfwKB3yXV&script=eNqVksFOwzAMhu99Ch8mdZNKua%2BaxDaQQGIXxAuExB1hTRw1rgSa9u54abf1UA4c2jrW78%2Bx%2F1 …
> [Bugfix] Fix DataBind multiple inconsistency

- CHANGELOG.md
- packages/docs/components/atoms/DataBind/data-bind-js-api.md
- packages/docs/components/atoms/DataBind/data-model-js-api.md
- packages/docs/components/atoms/DataBind/stories/basic.twig
- packages/docs/components/atoms/DataBind/stories/checkbox.twig
- packages/docs/components/atoms/DataBind/stories/checkboxes.twig
- packages/docs/components/atoms/DataBind/stories/compute-example.twig
- packages/docs/components/atoms/DataBind/stories/effect-example.twig
- packages/docs/components/atoms/DataBind/stories/select-multiple.twig
- packages/docs/components/atoms/DataBind/stories/select.twig
- packages/tests/atoms/DataBind.spec.ts
- packages/tests/atoms/DataModel.spec.ts
- packages/ui/atoms/Data/DataBind.ts
- packages/ui/atoms/Data/DataComputed.ts
- packages/ui/atoms/Data/DataEffect.ts
#288
The `name` option is reserved, so we rename it to `group`.
> [Feature] DataBind: rename the `name` option to `group`

- CHANGELOG.md
- packages/docs/components/atoms/Action/index.md
- packages/docs/components/atoms/Action/js-api.md
- packages/docs/components/atoms/Action/stories/multiple-events/app.js
- packages/docs/components/atoms/Action/stories/multiple-events/app.twig
- packages/tests/__utils__/components.ts
- packages/tests/__utils__/index.ts
- packages/tests/atoms/Action.spec.ts
- packages/tests/atoms/ActionEvent.spec.ts
- packages/tests/package.json
- packages/ui/atoms/Action/Action.ts
- packages/ui/atoms/Action/ActionEvent.ts
- tsconfig.json
#298 
This PR refactors the `Action` component to add support for multiple events. The existing API is still available, but we can now use new attributes to configure multiple events. 
```html
<button data-component="Action" data-option-on:click.prevent="App -> target.$update()">
Update the App
</button>
```
Event, targets and effect can now be configured with a single attribute with the following pattern:
```
data-option-on:<event>[.<modifier>]="[<target>(<selector>) -> ]<effect>"
```
Test it in [the playground](https://ui.studiometa.dev/-/play/#script=eNqtWG1v2zYQ%2Fp5fwQFBLWWOvH51kKZZmxUDVqxo8mGYGySsTNtqZUkgqbSZ6%2F%2B%2BOx7f9BIk6xogiUzePffCu%2BcoF9umlprt2K9ciSnLpeBanDfNlK2F%2Fr1Smle5UGzPVrLesslLpdtlUW%2BF5rNP6ljXdfm50JOTA49TqN%2FaKtdFXT2iNGt1UapY9UryShUPqrYFCB%2FkNTjFrs7fv7m4unl%2F8ebi …
> [Feature] Action: add support for multiple events

- CHANGELOG.md
- packages/docs/components/atoms/FigureShopify/examples.md
- packages/docs/components/atoms/FigureShopify/stories/reveal.css
- packages/docs/components/atoms/FigureShopify/stories/reveal.js
- packages/docs/components/atoms/FigureShopify/stories/reveal.liquid
- packages/docs/components/primitives/Transition/examples.md
- packages/docs/components/primitives/Transition/js-api.md
- packages/docs/components/primitives/Transition/stories/group/app.js
- packages/docs/components/primitives/Transition/stories/group/app.twig
- packages/tests/primitives/Transition.spec.ts
- packages/ui/decorators/withTransition.ts
#305 
This PR adds a new `group` option to the `Transition` component and its `withTransition` decorator. This enables defining multiple transition in the DOM that should be synced: when one enters, so do the others in the same group.
> [Transition] Add support for grouped transitions

- CHANGELOG.md
- packages/tests/Frame/AbstractFrameTrigger.spec.ts
- packages/tests/Frame/FrameForm.spec.ts
- packages/ui/Frame/AbstractFrameTrigger.ts
- packages/ui/Frame/FrameForm.ts
https://github.com/studiometa/js-toolkit/issues/627
This fixes a potential issue when extending the Frame components.
> [Bugfix] Frame refs and children access

- CHANGELOG.md
- packages/docs/components/Frame/js-api/frame-target.md
- packages/tests/Frame/FrameTarget.spec.ts
- packages/tests/package.json
- packages/ui/Frame/FrameTarget.ts
#394 
This PR fixes #394 by: 
- adding a new `morph` mode which will use [morphdom](https://github.com/patrick-steele-idem/morphdom) to update the `FrameTarget` children
- updatuing the `replace` mode to be a full replace of the `FrameTarget` children with the [`Element.replaceChildren()` method](https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceChildren)
> [Feature] FrameTarget: differentiate morph and replace modes

- CHANGELOG.md
- packages/ui/Accordion/Accordion.twig
- tests/__snapshots__/AccordionTest__it_renders_an_Accordion__default_is__open_option_is_set_to_true__the_first_item_overrides_the_config_to_false__1.txt
#433
When using the `Accordion.twig` template inside a `<form>` element, the button in the templating were triggering the form submission because they have no `type="button"` attribute.
This is fixed by adding a `type="button"` attribute.
> [Bugfix] Fix accordion triggering submit when used inside a form
